export const FETCHING_CONCERTS = 'FETCHING_CONCERTS';
export const FETCHING_CONCERTS_RESOLVED = 'FETCHING_CONCERTS_RESOLVED';
export const FETCHING_CONCERTS_REJECTED = 'FETCHING_CONCERTS_REJECTED';
export const ADDING_FAVORITE_CONCERTS = 'ADDING_FAVORITE_CONCERTS';
export const ADDING_FAVORITE_CONCERTS_RESOLVED = 'ADDING_FAVORITE_CONCERTS_RESOLVED';
export const ADDING_FAVORITE_CONCERTS_REJECTED = 'ADDING_FAVORITE_CONCERTS_REJECTED';